version: "3"
services:
  dev-main:
    image: zrr1999/zrr-main:latest
    tty: true
    privileged: true
    pid: host
    container_name: dev-main
    ports:
      - 10000:22
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/workspace:/workspace'
      - '~/micromamba/envs/cuda118:/nvidia/cuda118:r'
      - '/mnt:/mnt:r'
      - '~/.ssh:/root/.ssh:r'
    command: /bin/bash -c "/run.sh && zsh"
    restart: unless-stopped

  dev-paddle:
    image: zrr1999/zrr-paddle:latest
    tty: true
    privileged: true
    pid: host
    container_name: dev-paddle
    ports:
      - 10001:22
    volumes:
      - '~/workspace:/workspace'
      - '~/micromamba/envs/cuda118:/nvidia/cuda:r'
      - '/mnt:/mnt:r'
      - '~/.ssh:/root/.ssh:r'
    command: /bin/bash -c "/run.sh && zsh"
    restart: unless-stopped
